name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-08"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGZhMzhlOTEtNzc1Mi00MmYwLTkzMmYtMzUxZWEzMTlhNDI5IiwidGVuYW50X2lkIjoiMjk2ODE2YmM4ZjEyYjExNTIxN2FjMmI5MmMxOTk3ZTFmZTk0NGRkYWNkZGFhYzdiNDc5YjM0YTBhY2ZiNmE4NCIsImludGVybmFsX3NlY3JldCI6IjhhODU4NjBmLTZkMmYtNGE5OS05YmY4LTczZTg0MjBkYTFiNiJ9.nWL5gYRcJWcgEWZMV6-fxifX_mJTRvH0vG-CNhS5CJs"

JWT_SECRET = "devxaneesh18"